module.exports = {
	content: ['./app/**/*.{js,ts,jsx,tsx}'],
	plugins: [],
	fontFamily: {
		body: [
			'Raleway',
			'ui-sans-serif',
			'system-ui',
			'-apple-system',
			'system-ui',
			'Segoe UI',
			'Roboto',
			'Helvetica Neue',
			'Arial',
			'Noto Sans',
			'sans-serif',
			'Apple Color Emoji',
			'Segoe UI Emoji',
			'Segoe UI Symbol',
			'Noto Color Emoji',
		],
		sans: [
			'Raleway',
			'ui-sans-serif',
			'system-ui',
			'-apple-system',
			'system-ui',
			'Segoe UI',
			'Roboto',
			'Helvetica Neue',
			'Arial',
			'Noto Sans',
			'sans-serif',
			'Apple Color Emoji',
			'Segoe UI Emoji',
			'Segoe UI Symbol',
			'Noto Color Emoji',
		],
	},
};
